# Generated by Django 4.1.3 on 2022-12-01 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KNNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_neighbors', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('weights', models.CharField(choices=[('uniform', 'uniform'), ('distance', 'distance')], default='distance', max_length=8)),
                ('algorithm', models.CharField(choices=[('auto', 'auto'), ('ball_tree', 'ball_tree'), ('kd_tree', 'kd_tree'), ('brute', 'brute')], default='ball_tree', max_length=9)),
                ('leaf_size', models.IntegerField(default=31, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('p', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('metric', models.CharField(choices=[('braycurtis', 'braycurtis'), ('canberra', 'canberra'), ('chebyshev', 'chebyshev'), ('cityblock', 'cityblock'), ('dice', 'dice'), ('euclidean', 'euclidean'), ('hamming', 'hamming'), ('haversine', 'haversine'), ('infinity', 'infinity'), ('jaccard', 'jaccard'), ('kulsinski', 'kulsinski'), ('l1', 'l1'), ('l2', 'l2'), ('mahalanobis', 'mahalanobis'), ('manhattan', 'manhattan'), ('matching', 'matching'), ('minkowski', 'minkowski'), ('p', 'p'), ('pyfunc', 'pyfunc'), ('rogerstanimoto', 'rogerstanimoto'), ('russellrao', 'russellrao'), ('seuclidean', 'seuclidean'), ('sokalmichener', 'sokalmichener'), ('sokalsneath', 'sokalsneath'), ('wminkowski', 'wminkowski')], default='minkowski', max_length=14)),
                ('model_path', models.CharField(max_length=100, null=True)),
                ('train_score', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('test_score', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('cm_test_path', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
