# Generated by Django 4.1.3 on 2022-12-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knnmodel",
            name="metric",
            field=models.CharField(
                choices=[
                    ("chebyshev", "chebyshev"),
                    ("cityblock", "cityblock"),
                    ("euclidean", "euclidean"),
                    ("infinity", "infinity"),
                    ("l1", "l1"),
                    ("l2", "l2"),
                    ("manhattan", "manhattan"),
                    ("minkowski", "minkowski"),
                    ("p", "p"),
                ],
                default="minkowski",
                max_length=14,
            ),
        ),
    ]
